### ISSUE TITLE
JetBrains Mono is broken on Firefox

### ISSUE THREAD

**Issue by arjun44** [Xetera/xetera.dev#38]
![image](https://user-images.githubusercontent.com/41452613/181689993-4d10bf1a-665e-4a70-8c86-9067c67bf0b2.png)
From [this](https://xetera.dev/truthiness-equality/) article. Doesn't seem to happen on Chrom(e|ium)-based browsers.

If you change the font to a different one, the "distortion" (I don't know what to call it) doesn't seem to happen.

**Comment by Xetera** [comment]
Looks like there were some unused `font-feature-settings` that broke things on firefox. Thanks
